pub static DEBUG                        : bool = true;
pub static DEBUG_WITH_INPUT             : bool = false;
pub static DEBUG_SHOW_CHAR              : bool = false;
pub static DEBUG_SHOW_TOKEN             : bool = true;
pub static DEBUG_SHOW_TREE              : bool = true;
pub static DEBUG_SHOW_SYMBOL_TABLE      : bool = false;
pub static DEBUG_SHOW_ASSIGNMENT_TABLE  : bool = false;
pub static DEBUG_SHOW_RESULT            : bool = true;
pub static OUTPUT_VERBOSE               : bool = true; // include comments in generated code